name: Deploy to Staging

on:
    push: 
        branches: [main]

jobs:
    redeploy_everything:
        name: Deploy everything to the staging cluster
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: SSH into the EC2
              uses: appleboy/ssh-action@v1.2.1
              with:
                host: 65.1.93.188
                username: ubuntu
                key: ${{ secrets.KEY }}
                port: 22
                passphrase: ${{ secrets.PASSPHRASE }}
                script: |
                  cd /home/ubuntu/${{ github.event.repository.name }}/
                  git pull origin main
                  export PATH=/home/ubuntu/.nvm/versions/node/v22.14.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
                  sudo npm install -g pnpm
                  pnpm -v
                  pnpm install && pnpm run build
                  pm2 restart fe-server && pm2 restart http-server && pm2 restart ws-server 
